### ISSUE TITLE
Payload error on init with plugin with upload collection that has field with localized: true

### ISSUE THREAD

**Issue by DanRibbens** [richardvanbergen/payload-plugin-cloud-storage#14]
When my collection includes a localized field I get an error when Payload starts:

```ts
const Media: CollectionConfig = {
  slug: 'media',
  labels: {
    singular: 'Media',
    plural: 'Media',
  },
  access: {
    read: () => true,
  },
  upload: true,
  fields: [
    {
      name: 'alt',
      label: 'Alt Text',
      type: 'text',
      localized: true,
    },
  ],
};
```

This is the error I see:
```
TypeError: Cannot read property 'reduce' of undefined
    at text (C:\code\plugin-cloud-storage\node_modules\payload\src\mongoose\buildSchema.ts:96:43)
    at C:\code\plugin-cloud-storage\node_modules\payload\src\mongoose\buildSchema.ts:57:16
    at Array.forEach (<anonymous>)
    at Object.buildSchema [as default] (C:\code\plugin-cloud-storage\node_modules\payload\src\mongoose\buildSchema.ts:53:16)
    at Object.buildCollectionSchema [as default] (C:\code\plugin-cloud-storage\node_modules\payload\src\collections\buildSchema.ts:6:29)
    at C:\code\plugin-cloud-storage\node_modules\payload\src\collections\init.ts:19:31
    at Array.map (<anonymous>)
    at Object.registerCollections [as default] (C:\code\plugin-cloud-storage\node_modules\payload\src\collections\init.ts:16:51)
    at Payload.init (C:\code\plugin-cloud-storage\node_modules\payload\src\index.ts:146:20)
    at Object.<anonymous> (C:\code\plugin-cloud-storage\src\server.ts:8:9)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Module.m._compile (C:\code\plugin-cloud-storage\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.require.extensions.<computed> (C:\code\plugin-cloud-storage\node_modules\ts-node\src\index.ts:1059:12)       
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
```

I'm low on time so I can't investigate this any further right now. At this point I don't yet know if it is a problem in your plugin or Payload itself.
Removing `localized: true` fixes it.

**Comment by DanRibbens** [comment]
I was going too fast! My config didn't have locales, had nothing to do with Payload or your plugin. 🤦 Haha!
